################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.c \
E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.c 

OBJS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.o 

C_DEPS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.d 


# Each subdirectory must supply rules for building sources it contributes
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.o: E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"E:/IoT/Application/Funix_302_iot/Kalman/Kalman_filter" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"E:/IoT/Application/Funix_303_iot/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

